name: tests-windows
on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: number

jobs:
  better-sqlite3:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node-version }}
          cache: "pnpm"
      - uses: actions/download-artifact@v6
        with:
          name: build
          path: build/

      - run: pnpm install
      - run: cp .github/workflows/test/better-sqlite3.ormconfig.json ormconfig.json
      - run: pnpm exec c8 pnpm run test:ci

      - name: Coveralls Parallel
        uses: coverallsapp/github-action@v2
        with:
          flag-name: better-sqlite3-node:${{ inputs.node-version }}-windows
          parallel: true

  sqljs:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node-version }}
          cache: "pnpm"
      - uses: actions/download-artifact@v6
        with:
          name: build
          path: build/

      - run: pnpm install
      - run: cp .github/workflows/test/sqljs.ormconfig.json ormconfig.json
      - run: pnpm exec c8 pnpm run test:ci

      - name: Coveralls Parallel
        uses: coverallsapp/github-action@v2
        with:
          flag-name: sqljs-node:${{ inputs.node-version }}-windows
          parallel: true
